# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xc3gaKqxi_EN6hp2yj-iuJ5ek3Locnwn
"""

from google.colab import drive 
drive.mount('/content/gdrive')

import nltk,csv,numpy
nltk.download('punkt')
from nltk import sent_tokenize, word_tokenize, pos_tag
tokens=[]
reader = csv.reader(open('/content/gdrive/My Drive/itw practicals/ua.csv', 'rU'), delimiter= ",",quotechar='|')
for line in reader:
    for field in line:
      tokens.append(word_tokenize(field))
print(tokens)

#Stemming
from nltk.stem.porter import *
p_stemmer = PorterStemmer()
for words in tokens:
  for word in words:
    print(word+' --> '+p_stemmer.stem(word))

#Lemmatization
import spacy
nlp = spacy.load('en_core_web_sm')
/* */
def show_lemmas(text):
    for token in text:
        print(f'{token.text:{12}} {token.pos_:{6}} {token.lemma:<{22}} {token.lemma_}')

doc2 = nlp(u"i love to travel around the world")

show_lemmas(doc2)

